spring:
  application:
    name: db-service
server:
  port: 8300
 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:8302/eureka}